{
    {
        {
            {
                RightParamA = -0.5,
                Reflectance = 0,
                Color = Color3.new(0.294118, 0.592157, 0.294118),
                Velocity = Vector3.new(0, 0, 0),
                RightSurface = [==[Smooth]==],
                RotVelocity = Vector3.new(0, 0, 0),
                Material = [==[Plastic]==],
                FrontSurface = [==[Smooth]==],
                Size = Vector3.new(277, 1.2000000476837158, 277),
                Friction = 0.30000001192092896,
                BackSurface = [==[Smooth]==],
                BottomSurface = [==[Inlet]==],
                CanCollide = true,
                LeftSurfaceInput = [==[NoInput]==],
                RightSurfaceInput = [==[NoInput]==],
                CFrame = CFrame.new(136.5, 0.600000381, -115.5, 1, 0, 0, 0, 1, 0, 0, 0, 1),
                LeftSurface = [==[Smooth]==],
                Elasticity = 0.5,
                Transparency = 0,
                Name = [==[Part]==],
                ClassName = [==[Part]==],
                Orientation = Vector3.new(0, 0, 0),
                LeftParamA = -0.5,
                Shape = [==[Block]==],
                TopSurface = [==[Studs]==]
            },
            {
                RightParamA = -0.5,
                Reflectance = 0,
                Color = Color3.new(0.639216, 0.635294, 0.647059),
                Velocity = Vector3.new(0, 0, 0),
                RightSurface = [==[Smooth]==],
                RotVelocity = Vector3.new(0, 0, 0),
                Material = [==[Plastic]==],
                FrontSurface = [==[Smooth]==],
                Size = Vector3.new(16, 13.200000762939453, 277),
                Friction = 0.30000001192092896,
                BackSurface = [==[Smooth]==],
                BottomSurface = [==[Inlet]==],
                CanCollide = true,
                LeftSurfaceInput = [==[NoInput]==],
                RightSurfaceInput = [==[NoInput]==],
                CFrame = CFrame.new(6, 7.80000019, -115.5, 1, 0, 0, 0, 1, 0, 0, 0, 1),
                LeftSurface = [==[Smooth]==],
                Elasticity = 0.5,
                Transparency = 0,
                Name = [==[Part]==],
                ClassName = [==[Part]==],
                Orientation = Vector3.new(0, 0, 0),
                LeftParamA = -0.5,
                Shape = [==[Block]==],
                TopSurface = [==[Studs]==]
            },
            {
                RightParamA = -0.5,
                Reflectance = 0,
                Color = Color3.new(0.639216, 0.635294, 0.647059),
                Velocity = Vector3.new(0, 0, 0),
                RightSurface = [==[Smooth]==],
                RotVelocity = Vector3.new(0, 0, 0),
                Material = [==[Plastic]==],
                FrontSurface = [==[Smooth]==],
                Size = Vector3.new(16, 13.200000762939453, 277),
                Friction = 0.30000001192092896,
                BackSurface = [==[Smooth]==],
                BottomSurface = [==[Inlet]==],
                CanCollide = true,
                LeftSurfaceInput = [==[NoInput]==],
                RightSurfaceInput = [==[NoInput]==],
                CFrame = CFrame.new(267, 7.80000019, -115.5, 1, 0, 0, 0, 1, 0, 0, 0, 1),
                LeftSurface = [==[Smooth]==],
                Elasticity = 0.5,
                Transparency = 0,
                Name = [==[Part]==],
                ClassName = [==[Part]==],
                Orientation = Vector3.new(0, 0, 0),
                LeftParamA = -0.5,
                Shape = [==[Block]==],
                TopSurface = [==[Studs]==]
            },
            {
                RightParamA = -0.5,
                Reflectance = 0,
                Color = Color3.new(0.639216, 0.635294, 0.647059),
                Velocity = Vector3.new(0, 0, 0),
                RightSurface = [==[Smooth]==],
                RotVelocity = Vector3.new(0, 0, 0),
                Material = [==[Plastic]==],
                FrontSurface = [==[Smooth]==],
                Size = Vector3.new(16, 13.200000762939453, 245),
                Friction = 0.30000001192092896,
                BackSurface = [==[Smooth]==],
                BottomSurface = [==[Inlet]==],
                CanCollide = true,
                LeftSurfaceInput = [==[NoInput]==],
                RightSurfaceInput = [==[NoInput]==],
                CFrame = CFrame.new(136.5, 7.80000019, -246, 0, 0, -1, 0, 1, 0, 1, 0, 0),
                LeftSurface = [==[Smooth]==],
                Elasticity = 0.5,
                Transparency = 0,
                Name = [==[Part]==],
                ClassName = [==[Part]==],
                Orientation = Vector3.new(0, -90, 0),
                LeftParamA = -0.5,
                Shape = [==[Block]==],
                TopSurface = [==[Studs]==]
            },
            {
                RightParamA = -0.5,
                Reflectance = 0,
                Color = Color3.new(0.639216, 0.635294, 0.647059),
                Velocity = Vector3.new(0, 0, 0),
                RightSurface = [==[Smooth]==],
                RotVelocity = Vector3.new(0, 0, 0),
                Material = [==[Plastic]==],
                FrontSurface = [==[Smooth]==],
                Size = Vector3.new(16, 13.200000762939453, 245),
                Friction = 0.30000001192092896,
                BackSurface = [==[Smooth]==],
                BottomSurface = [==[Inlet]==],
                CanCollide = true,
                LeftSurfaceInput = [==[NoInput]==],
                RightSurfaceInput = [==[NoInput]==],
                CFrame = CFrame.new(136.5, 7.80000019, 15, 0, 0, -1, 0, 1, 0, 1, 0, 0),
                LeftSurface = [==[Smooth]==],
                Elasticity = 0.5,
                Transparency = 0,
                Name = [==[Part]==],
                ClassName = [==[Part]==],
                Orientation = Vector3.new(0, -90, 0),
                LeftParamA = -0.5,
                Shape = [==[Block]==],
                TopSurface = [==[Studs]==]
            },
            {
                RightParamA = -0.5,
                Reflectance = 0,
                Color = Color3.new(0.854902, 0.52549, 0.478431),
                Velocity = Vector3.new(0, 0, 0),
                RightSurface = [==[Smooth]==],
                RotVelocity = Vector3.new(0, 0, 0),
                Material = [==[Plastic]==],
                FrontSurface = [==[Smooth]==],
                Size = Vector3.new(16, 1.2000000476837158, 277),
                Friction = 0.30000001192092896,
                BackSurface = [==[Smooth]==],
                BottomSurface = [==[Inlet]==],
                CanCollide = true,
                LeftSurfaceInput = [==[NoInput]==],
                RightSurfaceInput = [==[NoInput]==],
                CFrame = CFrame.new(6, 15, -115.5, 1, 0, 0, 0, 1, 0, 0, 0, 1),
                LeftSurface = [==[Smooth]==],
                Elasticity = 0.5,
                Transparency = 0,
                Name = [==[Part]==],
                ClassName = [==[Part]==],
                Orientation = Vector3.new(0, 0, 0),
                LeftParamA = -0.5,
                Shape = [==[Block]==],
                TopSurface = [==[Studs]==]
            },
            {
                RightParamA = -0.5,
                Reflectance = 0,
                Color = Color3.new(0.854902, 0.52549, 0.478431),
                Velocity = Vector3.new(0, 0, 0),
                RightSurface = [==[Smooth]==],
                RotVelocity = Vector3.new(0, 0, 0),
                Material = [==[Plastic]==],
                FrontSurface = [==[Smooth]==],
                Size = Vector3.new(16, 1.2000000476837158, 245),
                Friction = 0.30000001192092896,
                BackSurface = [==[Smooth]==],
                BottomSurface = [==[Inlet]==],
                CanCollide = true,
                LeftSurfaceInput = [==[NoInput]==],
                RightSurfaceInput = [==[NoInput]==],
                CFrame = CFrame.new(136.5, 15, 15, 0, 0, -1, 0, 1, 0, 1, 0, 0),
                LeftSurface = [==[Smooth]==],
                Elasticity = 0.5,
                Transparency = 0,
                Name = [==[Part]==],
                ClassName = [==[Part]==],
                Orientation = Vector3.new(0, -90, 0),
                LeftParamA = -0.5,
                Shape = [==[Block]==],
                TopSurface = [==[Studs]==]
            },
            {
                RightParamA = -0.5,
                Reflectance = 0,
                Color = Color3.new(0.854902, 0.52549, 0.478431),
                Velocity = Vector3.new(0, 0, 0),
                RightSurface = [==[Smooth]==],
                RotVelocity = Vector3.new(0, 0, 0),
                Material = [==[Plastic]==],
                FrontSurface = [==[Smooth]==],
                Size = Vector3.new(16, 1.2000000476837158, 277),
                Friction = 0.30000001192092896,
                BackSurface = [==[Smooth]==],
                BottomSurface = [==[Inlet]==],
                CanCollide = true,
                LeftSurfaceInput = [==[NoInput]==],
                RightSurfaceInput = [==[NoInput]==],
                CFrame = CFrame.new(267, 15, -115.5, 1, 0, 0, 0, 1, 0, 0, 0, 1),
                LeftSurface = [==[Smooth]==],
                Elasticity = 0.5,
                Transparency = 0,
                Name = [==[Part]==],
                ClassName = [==[Part]==],
                Orientation = Vector3.new(0, 0, 0),
                LeftParamA = -0.5,
                Shape = [==[Block]==],
                TopSurface = [==[Studs]==]
            },
            {
                RightParamA = -0.5,
                Reflectance = 0,
                Color = Color3.new(0.854902, 0.52549, 0.478431),
                Velocity = Vector3.new(0, 0, 0),
                RightSurface = [==[Smooth]==],
                RotVelocity = Vector3.new(0, 0, 0),
                Material = [==[Plastic]==],
                FrontSurface = [==[Smooth]==],
                Size = Vector3.new(16, 1.2000000476837158, 245),
                Friction = 0.30000001192092896,
                BackSurface = [==[Smooth]==],
                BottomSurface = [==[Inlet]==],
                CanCollide = true,
                LeftSurfaceInput = [==[NoInput]==],
                RightSurfaceInput = [==[NoInput]==],
                CFrame = CFrame.new(136.5, 15, -246, 0, 0, -1, 0, 1, 0, 1, 0, 0),
                LeftSurface = [==[Smooth]==],
                Elasticity = 0.5,
                Transparency = 0,
                Name = [==[Part]==],
                ClassName = [==[Part]==],
                Orientation = Vector3.new(0, -90, 0),
                LeftParamA = -0.5,
                Shape = [==[Block]==],
                TopSurface = [==[Studs]==]
            },
            {
                RightParamA = -0.5,
                Reflectance = 0,
                Color = Color3.new(0.639216, 0.635294, 0.647059),
                Velocity = Vector3.new(0, 0, 0),
                RightSurface = [==[Smooth]==],
                RotVelocity = Vector3.new(0, 0, 0),
                Material = [==[Plastic]==],
                FrontSurface = [==[Smooth]==],
                Size = Vector3.new(19, 3.6000001430511475, 20),
                Friction = 0.30000001192092896,
                BackSurface = [==[Smooth]==],
                BottomSurface = [==[Inlet]==],
                CanCollide = true,
                LeftSurfaceInput = [==[NoInput]==],
                RightSurfaceInput = [==[NoInput]==],
                CFrame = CFrame.new(23.5, 3.00000048, -3, 1, 0, 0, 0, 1, 0, 0, 0, 1),
                LeftSurface = [==[Smooth]==],
                Elasticity = 0.5,
                Transparency = 0,
                Name = [==[Part]==],
                ClassName = [==[Part]==],
                Orientation = Vector3.new(0, 0, 0),
                LeftParamA = -0.5,
                Shape = [==[Block]==],
                TopSurface = [==[Studs]==]
            },
            {
                {
                    Transparency = 0,
                    Name = [==[Decal]==],
                    ClassName = [==[Decal]==],
                    Face = [==[Front]==],
                    Color3 = Color3.new(1, 1, 1),
                    Texture = [==[rbxasset://textures/face.png]==]
                },
                RightParamA = -0.5,
                Reflectance = 0,
                Color = Color3.new(0.639216, 0.635294, 0.647059),
                CFrame = CFrame.new(23, 10.3000011, -2, 1, 0, 0, 0, 1, 0, 0, 0, 1),
                RightSurface = [==[Smooth]==],
                RotVelocity = Vector3.new(0, 0, 0),
                Material = [==[Plastic]==],
                Velocity = Vector3.new(0, 0, 0),
                Size = Vector3.new(11, 11, 11),
                Friction = 0.30000001192092896,
                BackSurface = [==[Smooth]==],
                RightSurfaceInput = [==[NoInput]==],
                CanCollide = true,
                FrontSurface = [==[Smooth]==],
                BottomSurface = [==[Inlet]==],
                LeftSurfaceInput = [==[NoInput]==],
                LeftSurface = [==[Smooth]==],
                Elasticity = 0.5,
                Transparency = 0,
                Name = [==[Part]==],
                ClassName = [==[Part]==],
                Orientation = Vector3.new(0, 0, 0),
                LeftParamA = -0.5,
                Shape = [==[Ball]==],
                TopSurface = [==[Studs]==]
            },
            Name = [==[Workspace]==],
            ClassName = [==[Workspace]==]
        },
        {
            Name = [==[Lighting]==],
            ClassName = [==[Lighting]==]
        },
        {
            Name = [==[Teams]==],
            ClassName = [==[Teams]==]
        },
        {
            Name = [==[Folder]==],
            ClassName = [==[Folder]==]
        },
        {},
        Name = [==[Game]==],
        ClassName = [==[DataModel]==]
    }
}
